---
site_name: pyrula
site_description: Consulting
site_url: https://JanetVictorious.github.io/pyrula-software

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs

# repo_name: janetvictorious/ai-sample-pipelines
# repo_url: https://github.com/JanetVictorious/ai-sample-piplines

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Welcome:
      - pyrula: index.md
  - Solutions:
      - deliveries: solutions.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  # - search
  - include-markdown
  - mkdocstrings:
      default_handlers: python
      handlers:
        python:
          paths: [src]
          options:
            members_order: source
            heading_level: 3
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
